x-common-environment-vars: &common-env
  OLLAMA_MODEL: gemma3:4b # Changed back to a smaller model for faster setup
  CLIP_MODEL_NAME: clip-ViT-B-32
  NUM_IMAGES_TO_DOWNLOAD: 500

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/storage:/app/storage
    environment:
      <<: *common-env
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      init-backend:
        condition: service_completed_successfully
    restart: always
    # The command is now defined in the Dockerfile's CMD instruction

  init-backend:
    build: ./backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/storage:/app/storage
    environment:
      <<: *common-env
      OLLAMA_BASE_URL: http://ollama:11434
    depends_on:
      - ollama
    # --- The command is now simple and clean ---
    command: /app/docker-init.sh

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

volumes:
  ollama_data: